name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - "main"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build application .jar
        working-directory: ./gym-system
        run: mvn clean package -DskipTests


      - name: Docker Compose Build Application .jar
#        working-directory: ./springboot-gym-system
        run: docker compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/gym-system:latest ${{ secrets.DOCKER_USERNAME }}/gym-system:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gym-system:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gym-system:${{ github.run_id }}